### ISSUE TITLE
Is there a way to remote debug a spec launched from gauge maven plugin? 

### ISSUE THREAD

**Issue by raviu** [getgauge/gauge-maven-plugin#31]
Is it possible to debug step code using remote debug and gauge maven plugin? If someone knows how to do this, some steps would be really helpful.

**Comment by nehashri** [comment]
@raviu yes it is possible to do that. Here is how you can do that
- Open a port on the remote machine and make sure the port is accessible on your machine. Check if any proxy need to be enabled to do this.
- Set this environment variable `GAUGE_DEBUG_OPTS=<debug port>` and run gauge with the same commands with maven.
- If you are using Intellij you should be able to connect to the remote port as shown [here](https://stackoverflow.com/questions/21114066/attach-intellij-idea-debugger-to-a-running-java-process).(Make sure you connect the the right port and url). 

Hope this helps. 

PS: In future, could you please mail such queries in our google group (getgauge@googlegroups.com), so that you get better responses. Also refer [this](https://github.com/getgauge/gauge#talk-to-us) to see which platform is best to raise queries.

**Comment by raviu** [comment]
Brilliant, GAUGE_DEBUG_OPTS=<debug port> works as expected.
