### ISSUE TITLE
Gauge.writeMessage are shown in console when running with plugin

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge-maven-plugin#46]
If you have `Gauge.writeMessage("Hello, World!")` in your steps, and when running with plugin, the message `Hello, World!` is shown in console output.

We should have the ability to exclude the output.

```bash
Gauge version: 1.0.3

Plugins
-------
html-report (4.0.5)
java (0.6.9)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
hi @haroon-sheikh - i am trying to simulate this, but no luck. WIth gauge (1.0.3) and gauge-java (0.6.9) - both released versions as well as the latest nightlies of the two, when I do `gauge run specs` I get this:

```
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => /tmp/foo/foo/reports/html-report/index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped

Total time taken: 55ms
```

I think I am missing something - would be great if you can help reproduce this. Perhaps a docker image with this behaviour?

I am running this on linux.

**Comment by haroon-sheikh** [comment]
Hi @sriv, this only happens when you're using it maven plugin. i.e. `mvn gauge:execute -DspecsDir=specs/test.spec`

![image](https://user-images.githubusercontent.com/13623227/47995070-168c5780-e0ec-11e8-8067-01a9aaa3cb32.png)

**Comment by sriv** [comment]
It does not happen via gauge-maven plugin. I think I know what's going on.

This `CheckHAH` was a unintentional commit pushed by mistake and was reverted. But this was almost a year ago. See [gitter chat](https://gitter.im/getgauge/chat?at=59e5bb34e44c43700a422337)

Now since you say you are on `gauge 1.0.3` I think there might be another gauge binary somewhere that is picked up by `mvn`. 

Can you please check:

- does this happen on all machines?
- what does `which gauge` yield in the machines where you see this?

**Comment by haroon-sheikh** [comment]
@sriv `which gauge` returns `/usr/local/bin/gauge` on my machine which is `1.0.3`
but we have the same issue on running on older version `0.9.7` also inside a docker image.

**Comment by nehashri** [comment]
@haroon-sheikh I think the issue here is not with the Gauge version but the Gauge Java plugin version. 
Can you check the plugin location when you run Gauge, check if `GAUGE_HOME` environment variable is set anywhere and is pointing to a different location than the default. Can you also check the `gauge-java` version in your pom.xml file and see if the same version is used.

**Comment by haroon-sheikh** [comment]
Hi @nehashri, Yes you're right, think the issue is with `gauge-java:0.6.5` and when this is updated to later version, no longer console the outputs the messages.
