### ISSUE TITLE
New Gauge Maven project is not adding the latest gauge-java lib

### ISSUE THREAD

**Issue by kashishm** [getgauge/gauge-maven-plugin#6]

**Comment by mahendrakariya** [comment]
Gauge maven plugin is already updated with the latest gauge-java version and is [released](https://github.com/getgauge/gauge-maven-plugin/releases/tag/v1.0.2).

We will have to check if this issue that we saw today was due to some type in the selected archetype version.

I also tried to create a new gauge mvn project and it is referring to the latest gauge-java version.
